repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      # - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: debug-statements
        exclude: ^model_training/experiments/
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ^model_training/experiments/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^model_training/experiments/
        args: [
          "--profile", "black",
          "--src", "model_training/jaxrl_m",
          "--src", "model_training/experiments",
          "--src", "data_collection/orchestrator",
        ]
